[package]
org = "ballerinax"
name = "nats"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-nats"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "./lib/jnats-@nats.client.version@.jar"

[[platform.java11.dependency]]
path = "../native/build/libs/nats-native-@project.version@.jar"

[build-options]
observabilityIncluded=true
