[package]
org = "ballerinax"
name = "nats"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "./lib/jnats-@nats.client.version@.jar"
groupId = "io.nats"
artifactId = "jnats"
version = "@nats.client.version@"

[[platform.java11.dependency]]
path = "../native/build/libs/nats-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "nats"
version = "@project.version@"

[build-options]
observabilityIncluded=true
