[package]
org = "ballerinax"
name = "nats"
version = "native-test"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-nats"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.2.0"

[[platform.java11.dependency]]
path = "./lib/jnats-2.8.0.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "nats-native"
version = "native-test"
path = "../native/build/libs/nats-native-native-test.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.0.0"
path = "./lib/constraint-native-1.0.0.jar"

[build-options]
observabilityIncluded=true
