[package]
org = "ballerinax"
name = "nats"
version = "2.6.0"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-nats"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.4.0"

[[platform.java11.dependency]]
path = "./lib/jnats-2.16.0.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "nats-native"
version = "2.6.0"
path = "../native/build/libs/nats-native-2.6.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.1.0"
path = "./lib/constraint-native-1.1.0-20221122-134300-fc2d3aa.jar"

[build-options]
observabilityIncluded=true
