[package]
org = "ballerinax"
name = "nats"
version = "@toml.version@"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "./lib/jnats-@nats.client.version@.jar"

[[platform.java11.dependency]]
path = "../native/build/libs/nats-native-@project.version@.jar"

[build-options]
observabilityIncluded=true
