[package]
org = "ballerinax"
name = "nats"
version = "2.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "./lib/jnats-2.8.0.jar"

[[platform.java11.dependency]]
path = "../native/build/libs/nats-native-2.0.0-SNAPSHOT.jar"

[build-options]
observabilityIncluded=true
