[package]
org = "ballerinax"
name = "nats"
version = "2.2.2"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-nats"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.1"

[[platform.java11.dependency]]
path = "./lib/jnats-2.8.0.jar"

[[platform.java11.dependency]]
path = "../native/build/libs/nats-native-2.2.2-SNAPSHOT.jar"

[build-options]
observabilityIncluded=true
